name: Deploy Backend-MinIO to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arisdev2k2/backend-minio:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          MINIO_ENDPOINT: http://minio:9000
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_BUCKET: images
          REACT_APP_MINIO_API_URL: https://hust-cv-student-20215643.id.vn/minio/upload
          PORT: 3001
          MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: MINIO_ENDPOINT,MINIO_ACCESS_KEY,MINIO_SECRET_KEY,MINIO_BUCKET,REACT_APP_MINIO_API_URL,PORT,MINIO_ROOT_USER,MINIO_ROOT_PASSWORD
          script: |
            # Update code from repository
            cd ~/minio-backend
            git pull origin main

            # Create network if not exists
            if ! docker network ls | grep -q minio-network; then
              docker network create minio-network
            fi

            # Pull latest image
            docker pull arisdev2k2/backend-minio:latest
            docker-compose down

            # Run docker-compose with all environment variables
            MINIO_ENDPOINT="${MINIO_ENDPOINT}" \
            MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY}" \
            MINIO_SECRET_KEY="${MINIO_SECRET_KEY}" \
            MINIO_BUCKET="${MINIO_BUCKET}" \
            REACT_APP_MINIO_API_URL="${REACT_APP_MINIO_API_URL}" \
            PORT="${PORT}" \
            MINIO_ROOT_USER="${MINIO_ROOT_USER}" \
            MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD}" \
            docker-compose up -d

            # Clean up old images
            docker image prune -f